version: '3.0'

services:
  base:
    build:
      context: .
      dockerfile: ./docker/base/Dockerfile
      target: debug
    ports:
      - 8000:8000
      - 4040:4040
    networks:
      - host
    volumes:
      - ./:/go/basic_japanese
      - ./build:/build
    security_opt:
      - "seccomp:unconfined"
    depends_on:
      - db
      - redis
  db: 
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 4406:3306
    volumes:
      - db-store:/var/lib/mysql
    restart: unless-stopped
    networks:
      - host
  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    environment:
      - HOSTNAME=redis
      - REDIS_ARGS="--save 20 1 --loglevel warning --requirepass abcd1234"
    volumes:
      - cache:/data
    networks:
      - host
  redis-gui:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    networks:
      - host
networks:
  host:
volumes:
  db-store:
  cache:
    driver: local